### ISSUE TITLE
Decrease minimum required VRAM documented in README?

### ISSUE THREAD

**Issue by traversaro** [traversaro/mujoco-mjx-pixi-example#4]
It seems that updating the tutorial in https://github.com/traversaro/mujoco-mjx-pixi-example/pull/2 also affected the minimum required VRAM. With that change, now the training starts fine (even on WSL) on my laptop with 4GB NVIDIA GeForce GTX 1650 Ti. The training does not end as my laptop shut dows (probably due to thermal dissipanation problem, but it does not fail with out of memory errors as it happened before to me and @ruben-arts .

**Comment by ruben-arts** [comment]
I tested both of the examples. 

- Training Humanoid [0:26:15]
https://github.com/traversaro/mujoco-mjx-pixi-example/assets/12893423/09b532bf-50c9-4512-bbf3-ec00e55b4c85

- Training Quadruped [0:53:21]
https://github.com/traversaro/mujoco-mjx-pixi-example/assets/12893423/f374b3d7-6882-44cc-b7b0-b0a096f359ea

Run on NVIDIA GeForce RTX 3050 Ti Laptop GPU 4096MiB VRAM

Ran it both in the server and VS-Code 
This is a really cool example @traversaro :100:

**Comment by traversaro** [comment]
Great, thanks!
